const fs = require('fs');

const extraContent = {
    en: {
        onboardTitle: "Personalize Your Journey",
        onboardDesc: "Tell us a bit about yourself so we can guide you better.",
        onboardQ1: "Are you a first-time voter?",
        onboardQ2: "Have you registered to vote?",
        onboardA1Yes: "Yes",
        onboardA1No: "No",
        onboardA2Yes: "Yes, I am registered",
        onboardA2No: "No, I need to register",
        onboardBtn: "Start My Journey",
        stat1: "Core Steps",
        stat2: "Knowledge Cards",
        stat3: "Quiz Questions",
        stat4: "Free to Learn",
        feat1: "Journey",
        feat1Desc: "Follow the complete election process step by step",
        feat2: "Knowledge Base",
        feat2Desc: "Learn key concepts with interactive cards",
        feat3: "Timeline",
        feat3Desc: "See the election process as a timeline",
        feat4: "Voter ID Card",
        feat4Desc: "Explore your digital Voter ID",
        feat5: "Quiz",
        feat5Desc: "Test your knowledge and earn a certificate",
        feat6: "Resources",
        feat6Desc: "Explore useful guides and references",
        progS1: "Journey Progress",
        progS2: "Start your learning journey to track your progress",
        bot1: "Easy to Understand",
        bot1Desc: "Simple language for everyone",
        bot2: "Interactive Learning",
        bot2Desc: "Learn on any device",
        bot3: "Trusted Information",
        vsp: "Voter Service Portal",
        eciApp: "Election Commission of India",
        vha: "Voter Helpline App",
        vhaDesc: "Download the official mobile app"
    },
    hi: {
        onboardTitle: "अपनी यात्रा को व्यक्तिगत बनाएं",
        onboardDesc: "ताकि हम आपका बेहतर मार्गदर्शन कर सकें, अपने बारे में कुछ बताएं।",
        onboardQ1: "क्या आप पहली बार मतदाता हैं?",
        onboardQ2: "क्या आपने मतदान के लिए पंजीकरण किया है?",
        onboardA1Yes: "हाँ",
        onboardA1No: "नहीं",
        onboardA2Yes: "हाँ, मैं पंजीकृत हूँ",
        onboardA2No: "नहीं, मुझे पंजीकरण करना है",
        onboardBtn: "मेरी यात्रा शुरू करें",
        stat1: "मुख्य कदम",
        stat2: "ज्ञान कार्ड",
        stat3: "प्रश्नोत्तरी",
        stat4: "मुफ्त शिक्षा",
        feat1: "यात्रा",
        feat1Desc: "पूरी चुनाव प्रक्रिया को चरण दर चरण समझें",
        feat2: "ज्ञानकोष",
        feat2Desc: "इंटरैक्टिव कार्ड के साथ प्रमुख अवधारणाएं जानें",
        feat3: "टाइमलाइन",
        feat3Desc: "चुनाव प्रक्रिया को टाइमलाइन के रूप में देखें",
        feat4: "वोटर आईडी कार्ड",
        feat4Desc: "अपने डिजिटल वोटर आईडी का अन्वेषण करें",
        feat5: "प्रश्नोत्तरी",
        feat5Desc: "अपने ज्ञान का परीक्षण करें",
        feat6: "संसाधन",
        feat6Desc: "उपयोगी दिशानिर्देश देखें",
        progS1: "यात्रा की प्रगति",
        progS2: "अपनी प्रगति को ट्रैक करने के लिए सीखना शुरू करें",
        bot1: "समझने में आसान",
        bot1Desc: "सभी के लिए सरल भाषा",
        bot2: "इंटरएक्टिव लर्निंग",
        bot2Desc: "किसी भी डिवाइस पर सीखें",
        bot3: "विश्वसनीय जानकारी",
        vsp: "मतदाता सेवा पोर्टल",
        eciApp: "भारत निर्वाचन आयोग",
        vha: "वोटर हेल्पलाइन ऐप",
        vhaDesc: "आधिकारिक मोबाइल ऐप डाउनलोड करें"
    },
    mr: {
        onboardTitle: "तुमचा प्रवास वैयक्तिकृत करा",
        onboardDesc: "आम्ही तुम्हाला चांगल्या प्रकारे मार्गदर्शन करू शकू यासाठी तुमच्याबद्दल थोडे सांगा.",
        onboardQ1: "तुम्ही पहिल्यांदाच मतदान करणार आहात का?",
        onboardQ2: "तुम्ही मतदानासाठी नोंदणी केली आहे का?",
        onboardA1Yes: "होय",
        onboardA1No: "नाही",
        onboardA2Yes: "होय, मी नोंदणीकृत आहे",
        onboardA2No: "नाही, मला नोंदणी करायची आहे",
        onboardBtn: "माझा प्रवास सुरू करा",
        stat1: "मुख्य टप्पे",
        stat2: "ज्ञान कार्ड",
        stat3: "प्रश्नमंजुषा",
        stat4: "मोफत शिक्षण",
        feat1: "प्रवास",
        feat1Desc: "संपूर्ण निवडणूक प्रक्रिया टप्प्याटप्प्याने समजून घ्या",
        feat2: "ज्ञानकोष",
        feat2Desc: "परस्परसंवादी कार्डांसह मुख्य संकल्पना जाणून घ्या",
        feat3: "टाइमलाइन",
        feat3Desc: "निवडणूक प्रक्रिया टाइमलाइन म्हणून पहा",
        feat4: "मतदार ओळखपत्र",
        feat4Desc: "तुमचे डिजिटल मतदार ओळखपत्र पहा",
        feat5: "मंजुषा",
        feat5Desc: "तुमच्या ज्ञानाची चाचणी घ्या",
        feat6: "संसाधने",
        feat6Desc: "उपयुक्त मार्गदर्शक पहा",
        progS1: "प्रवासाची प्रगती",
        progS2: "तुमच्या प्रगतीचा मागोवा घेण्यासाठी शिकायला सुरुवात करा",
        bot1: "समजण्यास सोपे",
        bot1Desc: "सर्वांसाठी साधी भाषा",
        bot2: "परस्परसंवादी शिक्षण",
        bot2Desc: "कोणत्याही डिव्हाइसवर शिका",
        bot3: "विश्वसनीय माहिती",
        vsp: "मतदार सेवा पोर्टल",
        eciApp: "भारत निवडणूक आयोग",
        vha: "वोटर हेल्पलाइन ॲप",
        vhaDesc: "अधिकृत मोबाईल ॲप डाउनलोड करा"
    },
    ta: {
        onboardTitle: "உங்கள் பயணத்தை தனிப்பயனாக்குங்கள்",
        onboardDesc: "நாங்கள் சிறப்பாக வழிகாட்ட உங்களை பற்றி சிறிது கூறுங்கள்.",
        onboardQ1: "நீங்கள் முதல் முறை வாக்காளரா?",
        onboardQ2: "வாக்களிக்க பதிவு செய்துள்ளீர்களா?",
        onboardA1Yes: "ஆம்",
        onboardA1No: "இல்லை",
        onboardA2Yes: "ஆம், பதிவு செய்துள்ளேன்",
        onboardA2No: "இல்லை, பதிவு செய்ய வேண்டும்",
        onboardBtn: "பயணத்தை தொடங்கு",
        stat1: "முக்கிய படிகள்",
        stat2: "அறிவு அட்டைகள்",
        stat3: "வினாடி வினா கேள்விகள்",
        stat4: "இலவச கற்றல்",
        feat1: "பயணம்",
        feat1Desc: "முழு தேர்தல் செயல்முறையையும் படிப்படியாக பின்பற்றவும்",
        feat2: "அறிவு தளம்",
        feat2Desc: "ஊடாடும் அட்டைகளுடன் முக்கிய கருத்துகளை அறியவும்",
        feat3: "காலவரிசை",
        feat3Desc: "செயல்முறையை காலவரிசையாக பார்க்கவும்",
        feat4: "வாக்காளர் அடையாள அட்டை",
        feat4Desc: "உங்கள் டிஜிட்டல் வாக்காளர் அடையாள அட்டை",
        feat5: "வினாடி வினா",
        feat5Desc: "உங்கள் அறிவை சோதிக்கவும்",
        feat6: "வளங்கள்",
        feat6Desc: "பயனுள்ள வழிகாட்டிகளை ஆராயவும்",
        progS1: "பயண முன்னேற்றம்",
        progS2: "உங்கள் முன்னேற்றத்தை அறிய பயணத்தை தொடங்குங்கள்",
        bot1: "புரிந்துகொள்ள எளிதானது",
        bot1Desc: "அனைவருக்கும் எளிய மொழி",
        bot2: "ஊடாடும் கற்றல்",
        bot2Desc: "எந்த சாதனத்திலும் கற்றுக்கொள்ளுங்கள்",
        bot3: "நம்பகமான தகவல்",
        vsp: "வாக்காளர் சேவை போர்டல்",
        eciApp: "இந்திய தேர்தல் ஆணையம்",
        vha: "வாக்காளர் உதவி பயன்பாடு",
        vhaDesc: "அதிகாரப்பூர்வ மொபைல் பயன்பாட்டை பதிவிறக்குங்கள்"
    }
};

['en', 'hi', 'mr', 'ta'].forEach(lang => {
    let fileStr = fs.readFileSync(`i18n/${lang}.js`, 'utf8');
    
    // Extract JSON using regex from the file
    let jsonMatch = fileStr.match(/window\.translations\['${lang}'\] = ([\s\S]*);$/);
    if(jsonMatch) {
        let jsonObj = JSON.parse(jsonMatch[1]);
        jsonObj.appTranslations = { ...jsonObj.appTranslations, ...extraContent[lang] };
        
        const newFileStr = `window.translations = window.translations || {};\nwindow.translations['${lang}'] = ${JSON.stringify(jsonObj, null, 4)};`;
        fs.writeFileSync(`i18n/${lang}.js`, newFileStr);
    }
});

console.log("Success");
